apiVersion: apps/v1
kind: Deployment
metadata:
  name: loop-deployment
  labels:
    app: loop_request
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loop_request
  template:
    metadata:
      labels:
        app: loop_request
    spec:
      containers:
        - name: loop_request
          image: loop_request_image:latest
          ports:
            - containerPort: 80