apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: new-crds.com.person.control
spec:
  preserveUnknownFields: false
  group: com.person.control
  names:
    kind: new-crd
    listKind: new-crdList
    plural: new-crds
    singular: new-crd
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          description: new-crd is the Schema for the new-crd API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: new-crdSpec defines the desired state of new-crd
              properties:
                name:
                  description: My new-crd
                  type: string
              type: object
            status:
              description: new-crdStatus defines the observed state of new-crd
              properties:
                name:
                  type: string
              type: object
          type: object
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []